apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: omero
spec:
  instances: 1

  imageName: 'ghcr.io/cloudnative-pg/postgresql:15.3-2'

  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: omero
      owner: omero
      secret:
        name: omero-db-app 

  resources:
    requests:
      memory: 2Gi
      cpu: 100m
    limits:
      memory: 6Gi
      cpu: 2

  storage:
    size: 10Gi
    storageClass: zfs-csi
